version: 2.1

orbs:
  maven: circleci/maven@1.1
jobs:
  build: 
    docker:       
      - image: buildpack-deps:trusty        
    steps:
      - run:
          name: Setup Environment Variables
          command: |
            echo "export TOKEN=123" >> $BASH_ENV
            echo '{"foo": 0}' | jq .
  test: 
    docker:       
      - image: buildpack-deps:trusty        
    steps:
      - run:
          name: Setup Environment Variables
          command: |
            echo $TOKEN
workflows:
  buildandtest:
    jobs:
      - build
      - test:
          requires:
            - build